### ISSUE TITLE
Digit sign keys type during the normal mode

### ISSUE THREAD

**Issue by zhekaus** [lubokkanev/vim-everywhere#1]
Therefore combination 2w, 3dd, etc. don't work either. 
I must say, your idea is brilliant! However, as I see, you have suported only the simplest navigation by now.
I wish good luck and I hope you’ll support the whole bunch of vim’s keys! )

**Comment by lubokkanev** [comment]
That's correct, I haven't implemented any of the 'multi symbol' commands. I have an idea how it can be done, but I don't have the free time at the moment.

**Comment by lubokkanev** [comment]
Halfway there.

**Comment by zhekaus** [comment]
You are doing a great job! That's awesome. 
Btw, I've found a script to think about including into yours: [http://islashdot.blogspot.ru/2007/10/vim-everywhere-in-windows.html](url)

**Comment by lubokkanev** [comment]
Nice. That script has cool tooltips and does multi-key shortcuts nicely. If you like, you can collaborate on this project. You can also check [THES](https://github.com/mihaifm/vim.ahk)[E TH](https://github.com/rcmdnk/vim_ahk)[REE.](https://github.com/cknadler/vim-anywhere)

**Comment by lubokkanev** [comment]
This has been implemented a while ago. Just created a new release v3.0.0 containing it.
